### PR TITLE
prepare for adding prebuild binaries to releases

### PR DESCRIPTION
**Pull request by paulfitz**
This:
 * Merges latest upstream.
 * Eliminates custom build and test steps by placing test hooks in the library, rather than keeping them separate. Separate is clean, but places the burden of dealing with linking problems across all platforms on us.
 * Points `binary` section of package.json at our repo, so that binaries placed in github releases here get used automatically.

This is a cleaned up version of my own fork of node-sqlite3. The bulk is a fairly uneventful merge, with changes in https://github.com/gristlabs/node-sqlite3/commit/b9d81020dba0b585886b70579fc69dd771079b32

### CODE REVIEW

**Comment by paulfitz** [comment]
There is a trial run here: https://github.com/gristlabs/node-sqlite3/actions/runs/4016600020
With binaries collected here: https://github.com/gristlabs/node-sqlite3/releases/tag/v5.1.4-grist.7
(updated)

<s>A prepackaged install can't quite be tested prior to landing, but you can overwrite .node files compiled on your own OS with something downloaded.</s> (tweaked tagging, example of testing in next comment)

<s>I need to mint a new version number, sorry about that.</s> (done)

<s>macos-m1 will depend on finding a volunteer to run a self-hosted runner.</s> (thanks @dsagal)

**Comment by paulfitz** [comment]
Output can now be tested as follows:
```
mkdir trial
cd trial
yarn init # hit enter for everything
yarn add https://github.com/gristlabs/node-sqlite3#v5.1.4-grist.7 --verbose
```

The `yarn add` step hopefully finishes with something like:
```
node-pre-gyp info using node-pre-gyp@1.0.10
node-pre-gyp info using node@16.13.1 | linux | x64
node-pre-gyp info check checked for "/home/paulfitz/cvs/take2/trial/node_modules/@gristlabs/sqlite3/lib/binding/napi-v6-linux-glibc-x64/node_sqlite3.node" (not found)
node-pre-gyp http GET https://github.com/gristlabs/node-sqlite3/releases/download/v5.1.4-grist.7/napi-v6-linux-glibc-x64.tar.gz
node-pre-gyp info install unpacking napi-v6-linux-glibc-x64/node_sqlite3.node
```
If it starts building, then prebuilt versions didn't work out :(

Then try running `node` and see if:
```
require('@gristlabs/sqlite3').VERSION
```
runs and prints out `'3.40.0'`.

**Comment by dsagal** [comment]
Works on a Mac!
```
node-pre-gyp info using node-pre-gyp@1.0.10
node-pre-gyp info using node@14.17.0 | darwin | x64
node-pre-gyp info check checked for "/Users/dmitry/devel/trial7/node_modules/@gristlabs/sqlite3/lib/binding/napi-v6-darwin-unknown-x64/node_sqlite3.node" (not found)
node-pre-gyp http GET https://github.com/gristlabs/node-sqlite3/releases/download/v5.1.4-grist.7/napi-v6-darwin-unknown-x64.tar.gz
node-pre-gyp info install unpacking napi-v6-darwin-unknown-x64/node_sqlite3.node
node-pre-gyp info extracted file count: 1
[@gristlabs/sqlite3] Success: "/Users/dmitry/devel/trial7/node_modules/@gristlabs/sqlite3/lib/binding/napi-v6-darwin-unknown-x64/node_sqlite3.node" is installed via remote
node-pre-gyp info ok
```
and
```
> require('@gristlabs/sqlite3').VERSION
'3.40.0'
>
```

**Comment by paulfitz** [comment]
Thanks for confirming @dsagal!

**Review by georgegevoian — APPROVED** [review]
Looks good. Thanks @paulfitz.

**Pull request merged**
